### ISSUE TITLE
[BUG] zk-lib 0.12.2 update makes Assembly Analyst hang on data.lua

### ISSUE THREAD

**Issue by Miner239** [ZwerOxotnik/zk-lib#9]
Usually any information is enough to fix a bug, but, please, consider to provide more information now or **later**.

Please drop the `factorio-current.log` file or `factorio-previous.log` here
[factorio-current.log](https://github.com/ZwerOxotnik/zk-lib/files/10556161/factorio-current.log)

**Describe the bug**
Loading Assembly Analyst 1.1.11 and zk-lib 0.12.2 together makes Assembly Analyst hang on loading its data.lua

**Steps to reproduce**
1. Enable both mods
2. Start game
3. Hang

**Expected behavior**
Game loads normally

**Screenshots/Videos (If you have any)**

**Additional Information**
Reverting to zk-lib 0.11.12 fixes the problem.

**Comment by ZwerOxotnik** [comment]
I'm very confused, I have to check it several times to confirm it.

**Comment by ZwerOxotnik** [comment]
This is a very weird and unique case. It does load with this [https://github.com/ClaudeMetz/AssemblyAnalyst/blob/a3e2db981baf8c4fd22925290e562dd4fa03a9fd/modfiles/data.pho](https://github.com/ClaudeMetz/AssemblyAnalyst/blob/a3e2db981baf8c4fd22925290e562dd4fa03a9fd/modfiles/data.pho) as a Lua file and at the same time the AssemblyAnalyst's precompiled chunk seems to be fine at first glance, but it doesn't do anything as soon data.extend was done, it doesn't really explain the issue.

**Comment by ZwerOxotnik** [comment]
update: I'm checking another stuff.

**Comment by ZwerOxotnik** [comment]
Huh, interesting bug because of precompiled chunks.

**Comment by ZwerOxotnik** [comment]
stack traceback:  
\_\_zk-lib\_\_/experimental/lazyAPI.lua:1161: in function 'get\_current\_mod'  
\_\_zk-lib\_\_/experimental/lazyAPI.lua:1058: in function 'extend'  
data.pho:3: in main chunk  
(...tail calls...)

**Comment by ZwerOxotnik** [comment]
Alright, I'll publish the fix in ~5 minutes.

**Comment by ZwerOxotnik** [comment]
Uploaded the fix: https://mods.factorio.com/mod/zk-lib/downloads
